server:
  address:  192.168.146.138
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-swallow-size: 209715200

mybatis-flex:
  config-location:
    - classpath*:mapper/mybatis-config.xml
  mapper-locations:
    - classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false
  configurationProperties:
#    指定默认数据源，该名称需要与数据源下配置的数据源名称一致,默认第一个为默认数据源，多个用英文逗号分割
    defaultDb: gbase-8s,mysql
  datasource:
    gbase-8s:
      url: jdbc:gbasedbt-sqli://192.168.149.99:9088/bms_general_aa:GBASEDBTSERVER=dtpMng;delimident=y;SQLMODE=GBase;DB_LOCALE=zh_CN.57372;
      username: gbasedbt
      password: Ws-123456,.
      driver-class-name: com.gbasedbt.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    clickhouse:
      type: com.alibaba.druid.pool.DruidDataSource
      url: jdbc:clickhouse://192.168.149.82:8123/logdata?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
      username: scma
      password: ScmaFinanceWondersoft
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      databaseInit: classpath:clickhouse-init-database.sql
      schemaInit: classpath:clickhouse-init-schema.sql
      dataInit: classpath:clickhouse-init-data.sql
    mysql:
      username: root
      password: ws-123456
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.149.82:3306/dtpweb?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&allowMultiQueries=true
      type: com.alibaba.druid.pool.DruidDataSource
      databaseInit: classpath:mysql-init-database.sql
      schemaInit: classpath:mysql-init-schema.sql
      dataInit: classpath:mysql-init-data.sql
    sqlite:
      driver-class-name: org.sqlite.JDBC
      url: jdbc:sqlite:E://devSoft//sqlite//db//test.db
spring:
  datasource:
#    driverClassName: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://192.168.149.80:5236?schema="file-exchange"&clobAsString=1&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8
#    username: WONDERSOFT
#    password: ws-123456
#    mysql:
#      username: root
#      password: 123456
#      driverClassName: com.mysql.jdbc.Driver
#      url: jdbc:mysql://192.168.149.93:3306/dtpweb?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8&allowMultiQueries=true
#      type: com.alibaba.druid.pool.DruidDataSource

    # gbase
#    url: jdbc:gbasedbt-sqli://192.168.149.99:9088/mng:GBASEDBTSERVER=dtpMng;SQLMODE=GBase;DB_LOCALE=zh_CN.57372;
#    username: gbasedbt
#    password: Ws-123456,.
#    driver-class-name: com.gbasedbt.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 5
      minIdle: 5
      maxActive: 20
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 60000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 300000
      #指定获取连接时连接校验的sql查询语句
      validationQuery: "SELECT 1 from dual"
      #验证连接的有效性
      testWhileIdle: true
      #获取连接时候验证，会影响性能（不建议true）
      testOnBorrow: true
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: 20
      removeAbandoned: false
      removeAbandonedTimeout: 1800
      logAbandoned: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,stat
      keepAlive: true
#    fileSchema: classpath:file-exchange-schema-dm.sql
#    fileData: classpath:file-exchange-data-dm.sql
  sql:
    init:
      mode: always
      continue-on-error: true
      encoding: utf-8
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
#      schema-locations: classpath:file-exchange_quartz_meta-dm.sql
#      data-locations: classpath:file-exchange_report_data-dm.sql
  autoconfigure:
    exclude:
#      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.quartz.QuartzAutoConfiguration
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
springdoc:
  swagger-ui:
    path: /swagger-ui.html
pagehelper:
#  dialect: com.rtm.application.mybatisFlex.page.GBaseDialect
  helper-dialect: com.rtm.application.mybatisFlex.page.GBaseDialect
  reasonable: true

#pagehelper:
#  helper-dialect: mysql
#  reasonable: true
